/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.lapthorn.demo.serialization.app

import net.lapthorn.demo.serialization.cars.Car

fun main() {
    val car = Car("Ford")
    println("Car is ${car.name}")
}
